// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearNowPlayingInfo():Promise<void>;

export function FetchAnsembedSource(arg1:string):Promise<string>;

export function FetchMovieAPI(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FetchNakastreamSource(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function FetchNakastreamSubtitle(arg1:string):Promise<string>;

export function FetchUqloadSource(arg1:string):Promise<string>;

export function FetchVidaraStream(arg1:string,arg2:string):Promise<string>;

export function FetchVidzySource(arg1:string):Promise<string>;

export function FetchWebPageHTML(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetNakastreamConfig():Promise<Record<string, string>>;

export function GetRemoteServerInfo():Promise<Record<string, any>>;

export function LoginWithGoogle():Promise<main.UserProfile>;

export function OpenURL(arg1:string):Promise<void>;

export function ProxyHlsContent(arg1:string):Promise<string>;

export function SetNakastreamConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetNowPlayingInfo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number):Promise<void>;
