// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearNowPlayingInfo() {
  return window['go']['main']['App']['ClearNowPlayingInfo']();
}

export function FetchAnsembedSource(arg1) {
  return window['go']['main']['App']['FetchAnsembedSource'](arg1);
}

export function FetchMovieAPI(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchMovieAPI'](arg1, arg2, arg3);
}

export function FetchNakastreamSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchNakastreamSource'](arg1, arg2, arg3, arg4);
}

export function FetchNakastreamSubtitle(arg1) {
  return window['go']['main']['App']['FetchNakastreamSubtitle'](arg1);
}

export function FetchUqloadSource(arg1) {
  return window['go']['main']['App']['FetchUqloadSource'](arg1);
}

export function FetchVidaraStream(arg1, arg2) {
  return window['go']['main']['App']['FetchVidaraStream'](arg1, arg2);
}

export function FetchVidzySource(arg1) {
  return window['go']['main']['App']['FetchVidzySource'](arg1);
}

export function FetchWebPageHTML(arg1) {
  return window['go']['main']['App']['FetchWebPageHTML'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetNakastreamConfig() {
  return window['go']['main']['App']['GetNakastreamConfig']();
}

export function GetRemoteServerInfo() {
  return window['go']['main']['App']['GetRemoteServerInfo']();
}

export function LoginWithGoogle() {
  return window['go']['main']['App']['LoginWithGoogle']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProxyHlsContent(arg1) {
  return window['go']['main']['App']['ProxyHlsContent'](arg1);
}

export function SetNakastreamConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNakastreamConfig'](arg1, arg2, arg3);
}

export function SetNowPlayingInfo(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SetNowPlayingInfo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
